# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{headword}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jeff Rafter"]
  s.date = %q{2009-09-08}
  s.description = %q{Simplify adding usernames to your application.}
  s.email = %q{jeff@socialrange.org}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.textile"
  ]
  s.files = [
    "CHANGELOG.textile",
     "LICENSE",
     "README.textile",
     "Rakefile",
     "TODO.textile",
     "TUTORIAL.textile",
     "VERSION",
     "app/controllers/headword/users_controller.rb",
     "config/headword_routes.rb",
     "generators/headword/USAGE",
     "generators/headword/headword_generator.rb",
     "generators/headword/templates/README",
     "generators/headword/templates/factories.rb",
     "generators/headword/templates/migrations/create_users.rb",
     "generators/headword/templates/migrations/update_users.rb",
     "generators/headword/templates/show.html.erb",
     "generators/headword/templates/user.rb",
     "lib/headword.rb",
     "lib/headword/extensions/routes.rb",
     "lib/headword/user.rb",
     "rails/init.rb",
     "test/controllers/users_controller_test.rb",
     "test/models/user_test.rb",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/jeffrafter/headword}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.4}
  s.summary = %q{When your users are that vain.}
  s.test_files = [
    "test/controllers/users_controller_test.rb",
     "test/models/user_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rsl-stringex>, [">= 1.0.2"])
    else
      s.add_dependency(%q<rsl-stringex>, [">= 1.0.2"])
    end
  else
    s.add_dependency(%q<rsl-stringex>, [">= 1.0.2"])
  end
end
